indexing_tool = "{haxorg_root}/build/utils_debug/reflection_tool"
toolchain_include = "{haxorg_root}/toolchain/llvm/lib/clang/17/include"
output_directory = "{config_dir}/src/hlibssh2"
input = [ "{config_dir}/libssh2/include" ]
build_root = "{config_dir}/libssh2/build"
source_root = "{config_dir}/libssh2"
header_root = "{config_dir}/libssh2/include"
cmake_configure_options = ["-DBUILD_TESTS=OFF"]


[nim]
universal_import = [
  # "libssh2_config.nim"
]

with_header_imports = false
importx_structs = false
